# 配置端口号
server:
  port: 8000
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/admin_template?useUnicode=true&characterEncoding=utf8
  # 配置环境（dev 开发环境、prod 生产环境）
  profiles:
    active: dev
  # 配置国际化，basename 指定国际化文件前缀
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
  # Redis 配置
  redis:
    # Redis 服务器地址
    host: 120.26.184.41
    # 连接端口号
    port: 6379
    # 数据库索引（0 - 15）
    database: 0
    # 超时时间（毫秒）
    timeout: 10000
    # lettuce 参数
    lettuce:
      pool:
        # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-wait: -1
        # 最大空闲连接 默认为 8
        max-idle: 5
        # 最小空闲连接 默认为 0
        min-idle: 0
  # mail 配置
  mail:
    # SMTP 服务器地址
    host: smtp.163.com
    # 邮件服务器账号
    username: m_17730125031@163.com
    # 授权码
    password: KFYRVDQAUXLNBSUO
    # 配置端口号（默认使用 25，若项目发布到云服务器，需要开放相应端口 465，需要配置相关 ssl 协议）
    port: 465
    # 编码字符集采用 UTF-8
    default-encoding: UTF-8
    # 配置 ssl 协议（端口为 25 时，可以不用配置）
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  # 文件上传大小配置
  servlet:
    multipart:
      # 限制单个文件大小
      max-file-size: 10MB
      # 限制单次请求总文件大小
      max-request-size: 50MB
  # 设置 json 中日期显示格式
  jackson:
    # 设置显示格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置时区
    time-zone: GMT+8

# 阿里云配置信息
aliyun:
  # common 配置信息
  accessKeyId: LTAI4GEWZbLZocBzXKYEfmmq
  accessKeySecret: rZLsruKxWex2qGYVA3UsuBgW5B3uJQ
  # OSS 相关配置信息
  endPoint: http://oss-cn-beijing.aliyuncs.com
  bucketName: admin-vue-template
  domain: http://admin-vue-template.oss-cn-beijing.aliyuncs.com
  # SMS 短信服务
  regionId: cn-hangzhou
  signName: 后台管理系统
  templateCode: SMS_194050461
